package com.leadhunter;

/** Todos os enums do sistema em um arquivo só. */
class Enums {}

enum Nicho {
    CLINICA_MEDICA, CLINICA_ODONTO, CLINICA_ESTETICA, IMOBILIARIA, ECOMMERCE,
    RESTAURANTE, PROFISSIONAL_LIBERAL, PRESTADOR_LOCAL, CASA_DE_FESTA, CONSTRUTORA, OUTRO
}

enum CategoriaServico { AUTOMACAO, SITE, COMBO }

enum StatusSite { SIM, NAO, DESATUALIZADO, NAO_VERIFICADO }

enum StatusNegociacao {
    NAO_CONTATADO, TENTATIVA_1, TENTATIVA_2, TENTATIVA_3,
    EM_NEGOCIACAO, REUNIAO_AGENDADA, PROPOSTA_ENVIADA, FECHADO, PERDIDO
}

enum Canal { COLD_CALL, WHATSAPP, EMAIL, INSTAGRAM, PRESENCIAL }
